---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-controller
spec:
  project: default
  source:
    directory:
      recurse: false
    repoURL: https://github.com/sugardon-org/kubernetes-cert
    path: cert-manager/
    targetRevision: main
    # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L21
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
