---
# https://cert-manager.io/docs/usage/certificate/
# Concepts: https://cert-manager.io/docs/concepts/certificate/
# example doc
# https://www.ibm.com/docs/ja/cpfs?topic=cmcm-using-acme-issue-certificates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sugardon-com
spec:
  secretName: sugardon-com-tls
  dnsNames:
    - sugardon.com
    - "*.sugardon.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
