---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - ../../base
  - clusterissuer.yaml
  # Certificate is depend on namespace
  # - certificate.yaml
